//Emotion Dataset, 50 tweets containing all emotions. 
const emotionDataset = 
[
    "i should just relax for now but it feels so distinctly strange for me",
    "i feel loved because i programmed my computer to tell me it loves me",
    "im feeling a bit apprehensive about it as i dont know if my little note cards will stand out from the mass of talent on etsy",
    "i understood somewhere in my heart his feeling of decite and abandonment of all hope for ever trusting me again",
    "i feel like god has been gracious in answering prayers",
    "i thought i should be excited that im starting work but im feeling reluctant as ever",
    "i dont i feel amazed",
    "i start to feel agitated",
    "i remember feeling paranoid",
    "i know that i should feel some sort of melancholy but i don t",
    "i feel rather petty that i just dont have time to have someone talented like christine make it",
    "i feel like i have weird sugar issues that my hunger is all over the place",
    "i know you feel supporting an inept city manager who has cost the tax payers millions already with his bungling is important",
    "i had this strange feeling that she was incredibly distressed",
    "i feel like you didnt really care that alexis did that to me and you were irritated that i was even telling you",
    "i am not feeling horny im just letting baba see the emote",
    "i do feel picoult is a talented writer the subject matter put me in a state of depression",
    "i feel so lame complaining that for minutes i get some blurry vision and then have to take it easy the rest of the day",
    "i feel enthralled by the lyrics and the rhythm",
    "i wake up ill feel really really mad",
    "i feel whiney at the moment",
    "i say that to myself when i am unsure or feeling insecure about what others think of me",
    "im feeling pretty freakin fab",
    "i feel useless because i dont bring in any income",
    "i don t have a gigantic fabric stash so each piece feels very precious to me",
    "i am feeling rather bitter and rather defeated over a multitude of subjects but lets talk about the main one",
    "i had that feeling in a very very long while and i couldnt decide whether i liked it or not",
    "i feel the gentle press of the seed through the soil",
    "every time i meet a certain dog that has once bitten me",
    "i will make you feel amazing tonight i need you no",
    "ive found it has made a huge difference especially on the finger with my ring and the my skin feels so much softer and less irritated",
    "i feel the self pressured expectation to keep up to date with our family events so in order to assuage the guilt here we go",
    "i was grateful for each and every one but it still made me feel funny",
    "im the type who doesnt use a moisturizer as my skin is too oily so this product is designed to contain a ton of moisturizing ingredients that will make my skin feel lovely without oils",
    "i see anything that would cause me to feel fearful or distrustful of him",
    "im feeling a little saddened and troubled too sorry for a couple of friends who i wish i could give big hugs to",
    "i feel a bit strange saying it",
    "i feel a pleasant little buzz on my tongue and a clean refreshing taste",
    "i get really sweaty during these episodes and my stomach will feel really funny like i m free falling",
    "ive been feeling a little stressed and overwhelmed",
    "i imagine that in the end it might feel like you do about not fully loving",
    "i was supposed to be working on a grant application but feeling overwhelmed i decided to curl up with my computer and netflix",
    "i feel hated i feel like i dont belong and more and more i feel that i want to die",
    "i am much lighter now i feel extremely passionate about myself and my life yes me i do",
    "i don t mean to be rude but i don t feel i want to be troubled with the thoughts right now",
    "i could feel his breath on me and smell the sweet scent of him",
    "i am made to feel useless",
    "i can remember what it feels like to be enthralled by him i cant actually feel it",
    "ive just watched the above video for the first time and feel a bit bitchy for doing so but here are some of my thoughts on her outfits",
    "id be more use at that level which would make the job feel more worthwhile and the season is basically half as long"
]
;
